import type { Consultation, FeedPost, ModerationItem, SRCProject, SupportCase } from "@/lib/types";

export const feedPosts: FeedPost[] = [
  {
    id: "post-1",
    author: "UENR SRC",
    authorType: "official",
    authorInitials: "SRC",
    category: "Official",
    title: "Academic registration closes this Friday",
    body: "Complete your semester registration before 5:00 PM. Students experiencing portal issues should contact Academic Affairs early.",
    publishedAt: "18 min ago",
    audience: "All students",
    priority: "urgent",
    likes: 248,
    comments: 31,
    deadline: "17 Jul",
  },
  {
    id: "post-2",
    author: "UENR Tech Community",
    authorType: "organization",
    authorInitials: "TC",
    category: "Opportunities",
    title: "Build for Bono: student innovation challenge",
    body: "Pitch a practical solution for energy, climate or campus life. Teams of two to five students are welcome.",
    image: "/images/uenr-event.jpg",
    publishedAt: "2 hr ago",
    audience: "All students",
    priority: "important",
    likes: 184,
    comments: 22,
    deadline: "24 Jul",
  },
  {
    id: "post-3",
    author: "Entertainment Committee",
    authorType: "organization",
    authorInitials: "EC",
    category: "Events",
    title: "Jama night returns to the auditorium",
    body: "An evening of campus culture, music and community. Student ID is required at entry.",
    image: "/images/campus-jama.jpg",
    publishedAt: "Yesterday",
    audience: "Sunyani campus",
    priority: "normal",
    likes: 612,
    comments: 84,
  },
  {
    id: "post-4",
    author: "Ama Serwaa",
    authorType: "student",
    authorInitials: "AS",
    category: "Student life",
    title: "Volunteers needed for the campus clean-up",
    body: "We are meeting behind the library at 6:30 AM on Saturday. Gloves and refreshments will be provided.",
    publishedAt: "Yesterday",
    audience: "Sunyani campus",
    priority: "normal",
    likes: 96,
    comments: 14,
  },
  {
    id: "post-5",
    author: "School of Engineering Society",
    authorType: "organization",
    authorInitials: "SES",
    category: "Academics",
    title: "Peer tutorial timetable is now available",
    body: "Calculus, thermodynamics and circuit theory sessions run throughout the week in Engineering Block B.",
    image: "/images/src-community.jpg",
    publishedAt: "2 days ago",
    audience: "School of Engineering",
    priority: "normal",
    likes: 131,
    comments: 19,
  },
];

export const supportCases: SupportCase[] = [
  { id: "SRC-260714-1042", category: "Facilities", title: "Lecture hall lighting issue", createdAt: "12 Jul", updatedAt: "Today, 09:42", status: "Assigned", assignedTo: "Welfare Committee", private: false },
  { id: "SRC-260708-0918", category: "Academic", title: "Missing continuous assessment record", createdAt: "8 Jul", updatedAt: "11 Jul, 15:20", status: "In review", assignedTo: "Academic Affairs Liaison", private: true },
  { id: "SRC-260701-0834", category: "Welfare", title: "Water supply interruption", createdAt: "1 Jul", updatedAt: "4 Jul, 12:05", status: "Resolved", assignedTo: "Welfare Committee", private: false },
];

export const projects: SRCProject[] = [
  {
    id: "project-1",
    title: "Extended library study hours",
    summary: "Pilot later closing hours during examination periods across the main library spaces.",
    owner: "Academic Committee",
    progress: 75,
    status: "In progress",
    updatedAt: "10 Jul 2026",
    milestones: [
      { label: "Student needs survey", complete: true },
      { label: "Library management approval", complete: true },
      { label: "Four-week pilot", complete: true },
      { label: "Publish pilot results", complete: false },
    ],
  },
  {
    id: "project-2",
    title: "Campus lighting improvement",
    summary: "Map and escalate poorly lit routes used by students after evening lectures.",
    owner: "Welfare & Security",
    progress: 48,
    status: "In progress",
    updatedAt: "8 Jul 2026",
    milestones: [
      { label: "Safety walk and mapping", complete: true },
      { label: "Submit priority locations", complete: true },
      { label: "Installation phase", complete: false },
      { label: "Student verification walk", complete: false },
    ],
  },
  {
    id: "project-3",
    title: "Student opportunity desk",
    summary: "A verified weekly digest of scholarships, internships and competitions.",
    owner: "SRC Secretariat",
    progress: 100,
    status: "Completed",
    updatedAt: "27 Jun 2026",
    milestones: [
      { label: "Verification workflow", complete: true },
      { label: "Partner outreach", complete: true },
      { label: "First digest published", complete: true },
    ],
  },
];

export const consultation: Consultation = {
  id: "poll-1",
  question: "Which library closing time would help you most during exams?",
  description: "Your response will be included in the report presented to library management.",
  closesAt: "Closes 18 Jul, 6:00 PM",
  responses: 1248,
  options: [
    { id: "10pm", label: "10:00 PM", votes: 312 },
    { id: "midnight", label: "12:00 midnight", votes: 704 },
    { id: "2am", label: "2:00 AM", votes: 232 },
  ],
};

export const moderationQueue: ModerationItem[] = [
  { id: "mod-1", author: "Kofi Mensah", title: "Found student ID near the library", category: "Student life", submittedAt: "8 min ago", risk: "Low" },
  { id: "mod-2", author: "Nana Yaa", title: "Departmental football trials this weekend", category: "Sports", submittedAt: "23 min ago", risk: "Low" },
  { id: "mod-3", author: "Anonymous account flag", title: "Unverified accommodation promotion", category: "Student life", submittedAt: "51 min ago", risk: "Review" },
];
